/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arena;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author SERGIO
 */
public class panel extends javax.swing.JPanel {

    
    int vx[]={75,231,153,75,231};
    int vy[]={20,20,98,173,173};
    int np=5;
    // punto en comun x=153 y=230
    
    
    // TRIANGULO DE ARRIBA 
    int vx1[]={76,230,152};
    int vy1[]={21,21,97};
    int np1=3;
    
    // TRIANGULO DE ABAJO
    int vx2[]={75,231,153};
    int vy2[]={173,173,173};
    int np2=3;
    
  
    
    public void paintComponent(Graphics g){
        
        
        super.paintComponent(g);
        
        g.setColor(Color.yellow);
        g.drawPolygon(vx, vy,np);
        
       
        g.setColor(Color.red);
        g.fillPolygon(vx1, vy1, np1);
        
       
        g.setColor(Color.red);
        g.fillPolygon(vx2, vy2, np2);
    
    }
    
    
    
    
    
    
    public panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
